#' Load triangular co-expression (MI or CLR) matrix generated by genepair
#'
#' @param geneIds Gene identifiers to apply to the rownames and colnames
#' @param filename Path to the triangular matrix file
#'
#' @return A symmetrical matrix
#'
loadTriMatrix <- function(geneIds,filename){
  n <- length(geneIds)
  m <- matrix(0, ncol = n, nrow = n, dimnames = list(geneIds, geneIds) )
  inCon <- file(filename, "rt")
  for(i in 1:(n-1)){
    # read one line at the time
    x <- scan(inCon,nlines = 1,quiet = T)
    # write row-wise
    m[i+1, 1:i] <- x
    # write column-wise
    m[1:i, i+1] <- x
  }
  close(inCon)
  return(m)
}