#' Load triangular co-expression (MI or CLR) matrix generated by genepair
#'
#' @param geneIds Gene identifiers to apply to the rownames and colnames
#' @param filename Path to the triangular matrix file
#'
#' @return A symmetrical matrix
#'
loadTriMatrix <- function(geneIds,filename){
  n <- length(geneIds)
  m <- matrix(0, ncol = n, nrow = n )
  m[upper.tri(m)] <- scan(file=filename)
  gc() # free some memory
  m <- m + t(m) # fill in the other half of the matrix
  gc() # free some memory
  rownames(m) <- geneIds
  colnames(m) <- geneIds
  return(m)
}